### ISSUE TITLE
As a new user, I want to be able to turn a list of songs in text form into a playlist on a platform

### ISSUE THREAD

**Issue by cjhet02** [ChicoState/MusicMirror#4]
Based on the Spotify API docs, the general flow will look something like this:

1. Authorize Spotify connection
2. Parse text list
3. Iterate through list and create a list of matching songs on Spotify ([api req](https://developer.spotify.com/documentation/web-api/reference/search))
4. if list size > 0, create playlist ([api req](https://developer.spotify.com/documentation/web-api/reference/create-playlist))
5. Iterate through list of matches and add each song to the playlist ([api req](https://developer.spotify.com/documentation/web-api/reference/add-tracks-to-playlist))

**Comment by khasek** [comment]
What information would we be saving about each song?
