### ISSUE TITLE
Login to Spotify logs out of YouTube and vis versa 

### ISSUE THREAD

**Issue by Angel086** [ChicoState/MusicMirror#61]
When logging in to spot it logs you out of youtube if you log in an dif you log in again to youtube it logs you out of spotify, but if you log in to youtube then spotify and do a search it works, for both searching but if the other way it doesn't allow the search

**Comment by khasek** [comment]
I now have it so that either service does not log the other out (yt_cleanup branch). Mostly the login/out seems to be operational now, although I'm still having trouble logging into YouTube after loggin into Spotify (but not the other way around).
